name: splay
description: SPlay - Music Player

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  file_picker: ^10.1.9
  filepicker_windows: ^2.1.4
  flutter_media_metadata: ^1.0.0+1
  get: ^4.7.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  uuid: ^4.5.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5

flutter:

  uses-material-design: true